### ISSUE TITLE
PostgreSQL 9.6 segfault

### ISSUE THREAD

**Issue by tirrolo** [PierreSenellart/provsql#13] opened 2019-02-08 10:16 UTC
I am trying provsql on the tables from the Berlin SPARQL Benchmark. I am testing the version before the latest one in January. The following query (not using provenance) causes a segmentation fault:

SELECT *
FROM (
SELECT DISTINCT 
   1 AS "offerQuestType", NULL AS "offerLang", CAST("Qpublic_offerVIEW0"."nr" AS VARCHAR(10485760)) AS "offer"
FROM 
    "public"."offer" "Qpublic_offerVIEW0"
WHERE 
    "Qpublic_offerVIEW0"."price" IS NOT NULL
) SUB_QVIEW

**Comment by tirrolo** [comment] 2019-02-08 10:49
Update: It seems like it does not like the "IS NOT NULL" part:

select nr from offer where price is not null;

already fails.

**Comment by PierreSenellart** [comment] 2019-02-08 13:34
Thanks for the bug report, I will have a look as soon as possible, but quite busy right now; I suspect there is an issue with handling of NULLs. In the mean time, you can try and disable where provenance support if you don't need it ("set provsql.where_provenance=off;" in any connection to the database) in case the problem is related to where provenance management.

**Comment by tirrolo** [comment] 2019-02-08 13:55
Thanks for your reply. I tried and indeed the query executes if I turn that option off.

**Comment by PierreSenellart** [comment] 2019-02-11 11:34
The issue has been fixed in b87c175. Thanks again for the bug report. Two points:

- If you don't need where provenance, you are better off disabling it for now, as it has a non-negligible impact on performance (and, likely, on stability)
- I welcome other bug reports, the system certainly needs to be stress tested with various query features.

**Closed by PierreSenellart** 2019-02-11 11:34 UTC
